/* L2 frozen typed in-memory views. Generated by tests/contract/projected-light/generate_views.py. */
#ifndef MANTIS_SEMANTIC_VIEWS_H
#define MANTIS_SEMANTIC_VIEWS_H
#include <mantis/plugin.h>
#ifdef __cplusplus
extern "C" {
#endif
#define MANTIS_ACQUISITION_PROGRAM "org.mantis.AcquisitionProgram"
#define MANTIS_ACQUISITION_BUNDLE "org.mantis.AcquisitionBundle"
#define MANTIS_ACQUISITION_EVIDENCE "org.mantis.AcquisitionEvidence"
#define MANTIS_TRIGGER_EVENT "org.mantis.TriggerEvent"
#define MANTIS_LASER_OBSERVATION "org.mantis.LaserObservation"
#define MANTIS_MAX_BUNDLE_MEMBERS 64u
#define MANTIS_MAX_PROGRAM_STEPS 256u
#define MANTIS_MAX_PARTICIPANTS 64u
#define MANTIS_MAX_SEMANTIC_ENTRIES 4096u
/* Strings: NUL terminated UTF-8, <=1024 bytes (identities <=256).
 * Evidence: established iff value != NULL; unknown/unavailable require NULL.
 * Arrays: NULL iff count == 0; counts bounded by L1 and the total view budget.
 * Every view is borrowed synchronously. Retained bulk storage uses MantisBuffer.
 * No recursive graphs: data children are only FrameSet -> ImageFrame.
 */
enum { MANTIS_PRESENCE_ESTABLISHED = 0u, MANTIS_PRESENCE_UNKNOWN = 1u,
       MANTIS_PRESENCE_UNAVAILABLE = 2u };

enum { MANTIS_EVIDENCE_METHOD_SOFTWARE_DISPATCH = 0u, MANTIS_EVIDENCE_METHOD_CONTROLLER_REPORT = 1u, MANTIS_EVIDENCE_METHOD_REGISTER_READBACK = 2u, MANTIS_EVIDENCE_METHOD_ELECTRICAL_READBACK = 3u, MANTIS_EVIDENCE_METHOD_OPTICAL_SENSOR = 4u, MANTIS_EVIDENCE_METHOD_VALIDATED_EXECUTOR = 5u, MANTIS_EVIDENCE_METHOD_CAMERA_METADATA = 6u, MANTIS_EVIDENCE_METHOD_SOFTWARE_ASSOCIATION = 7u, MANTIS_EVIDENCE_METHOD_IMPORTED = 8u };
enum { MANTIS_EVIDENCE_SCOPE_CONTROLLER_REGISTER = 0u, MANTIS_EVIDENCE_SCOPE_ELECTRICAL_ENABLE = 1u, MANTIS_EVIDENCE_SCOPE_OPTICAL_EMISSION = 2u };
enum { MANTIS_EMITTER_STATE_OFF = 0u, MANTIS_EMITTER_STATE_ON = 1u };
enum { MANTIS_ACKNOWLEDGEMENT_STAGE_ACCEPTANCE = 0u, MANTIS_ACKNOWLEDGEMENT_STAGE_COMPLETION = 1u };
enum { MANTIS_ACKNOWLEDGEMENT_RESULT_SUCCESS = 0u, MANTIS_ACKNOWLEDGEMENT_RESULT_REJECTED = 1u, MANTIS_ACKNOWLEDGEMENT_RESULT_FAILED = 2u };
enum { MANTIS_TIMESTAMP_MEANING_EXPOSURE_START = 0u, MANTIS_TIMESTAMP_MEANING_EXPOSURE_END = 1u, MANTIS_TIMESTAMP_MEANING_DRIVER_DELIVERY = 2u, MANTIS_TIMESTAMP_MEANING_DEVICE_EVENT = 3u };
enum { MANTIS_ASSOCIATION_METHOD_NATIVE_TRIGGER = 0u, MANTIS_ASSOCIATION_METHOD_VALIDATED_EXECUTOR = 1u, MANTIS_ASSOCIATION_METHOD_SOFTWARE_CORRESPONDENCE = 2u, MANTIS_ASSOCIATION_METHOD_IMPORTED = 3u };
enum { MANTIS_SYNC_QUALITY_UNKNOWN = 0u, MANTIS_SYNC_QUALITY_SOFTWARE = 1u, MANTIS_SYNC_QUALITY_HARDWARE = 2u };
enum { MANTIS_CAPTURE_MODE_NONE = 0u, MANTIS_CAPTURE_MODE_FREE_RUNNING = 1u, MANTIS_CAPTURE_MODE_HARDWARE_TRIGGER = 2u };
enum { MANTIS_EVIDENCE_REQUIREMENT_COMMANDED_ONLY = 0u, MANTIS_EVIDENCE_REQUIREMENT_CONTROLLER_ACKNOWLEDGED = 1u, MANTIS_EVIDENCE_REQUIREMENT_EXPOSURE_EFFECTIVE = 2u };
enum { MANTIS_TRIGGER_KIND_REQUESTED = 0u, MANTIS_TRIGGER_KIND_ACKNOWLEDGED_ACCEPTED = 1u, MANTIS_TRIGGER_KIND_ACKNOWLEDGED_COMPLETED = 2u, MANTIS_TRIGGER_KIND_REJECTED = 3u, MANTIS_TRIGGER_KIND_OBSERVED = 4u, MANTIS_TRIGGER_KIND_TIMED_OUT = 5u, MANTIS_TRIGGER_KIND_CANCELLED = 6u };
enum { MANTIS_ACQUISITION_DISPOSITION_STARTUP = 0u, MANTIS_ACQUISITION_DISPOSITION_CAPTURED = 1u, MANTIS_ACQUISITION_DISPOSITION_CONTROL_ONLY = 2u, MANTIS_ACQUISITION_DISPOSITION_COMPLETED = 3u, MANTIS_ACQUISITION_DISPOSITION_FAILED = 4u, MANTIS_ACQUISITION_DISPOSITION_STOPPED = 5u, MANTIS_ACQUISITION_DISPOSITION_CANCELLED = 6u };
enum { MANTIS_ACQUISITION_REASON_NONE = 0u, MANTIS_ACQUISITION_REASON_TIMEOUT = 1u, MANTIS_ACQUISITION_REASON_REJECTED = 2u, MANTIS_ACQUISITION_REASON_DEVICE_FAILURE = 3u, MANTIS_ACQUISITION_REASON_TRANSPORT_FAILURE = 4u, MANTIS_ACQUISITION_REASON_EVIDENCE_MISSING = 5u, MANTIS_ACQUISITION_REASON_CONTRADICTORY_EVIDENCE = 6u, MANTIS_ACQUISITION_REASON_RESOURCE_LIMIT = 7u, MANTIS_ACQUISITION_REASON_USER_STOP = 8u, MANTIS_ACQUISITION_REASON_USER_CANCEL = 9u, MANTIS_ACQUISITION_REASON_CLEANUP_FAILURE = 10u };
enum { MANTIS_LOSS_KIND_COMMAND = 0u, MANTIS_LOSS_KIND_TRIGGER = 1u, MANTIS_LOSS_KIND_FRAME = 2u, MANTIS_LOSS_KIND_EXPOSURE = 3u, MANTIS_LOSS_KIND_BUNDLE = 4u, MANTIS_LOSS_KIND_RECORD = 5u, MANTIS_LOSS_KIND_EXCLUDED_FRAME = 6u };
enum { MANTIS_OBSERVATION_ORIGIN_REAL = 0u, MANTIS_OBSERVATION_ORIGIN_SYNTHETIC = 1u, MANTIS_OBSERVATION_ORIGIN_IMPORTED = 2u };
enum { MANTIS_OBSERVATION_DISPOSITION_SUCCESS = 0u, MANTIS_OBSERVATION_DISPOSITION_EXTRACTOR_FAILED = 1u, MANTIS_OBSERVATION_DISPOSITION_EXTRACTOR_UNAVAILABLE = 2u };
typedef struct MantisDataTypeV1 MantisDataTypeV1;
typedef struct MantisHashV1 MantisHashV1;
typedef struct MantisVersionV1 MantisVersionV1;
typedef struct MantisCalibrationReferenceV1 MantisCalibrationReferenceV1;
typedef struct MantisClockDomainV1 MantisClockDomainV1;
typedef struct MantisCoordinateFrameV1 MantisCoordinateFrameV1;
typedef struct MantisSyncGroupV1 MantisSyncGroupV1;
typedef struct MantisClockMappingV1 MantisClockMappingV1;
typedef struct MantisStepInstanceV1 MantisStepInstanceV1;
typedef struct MantisStreamIdentityV1 MantisStreamIdentityV1;
typedef struct MantisSourceFrameKeyV1 MantisSourceFrameKeyV1;
typedef struct MantisFrameSetKeyV1 MantisFrameSetKeyV1;
typedef struct MantisBundleKeyV1 MantisBundleKeyV1;
typedef struct MantisEvidenceKeyV1 MantisEvidenceKeyV1;
typedef struct MantisTriggerKeyV1 MantisTriggerKeyV1;
typedef struct MantisNativeTriggerIdentityV1 MantisNativeTriggerIdentityV1;
typedef struct MantisContentReferenceV1 MantisContentReferenceV1;
typedef struct MantisProgramReferenceV1 MantisProgramReferenceV1;
typedef struct MantisExactCalibrationReferenceV1 MantisExactCalibrationReferenceV1;
typedef struct MantisClockIdentityV1 MantisClockIdentityV1;
typedef struct MantisSemanticTimestampV1 MantisSemanticTimestampV1;
typedef struct MantisRuntimeTimestampV1 MantisRuntimeTimestampV1;
typedef struct MantisTimeIntervalV1 MantisTimeIntervalV1;
typedef struct MantisClockMappingEvidenceV1 MantisClockMappingEvidenceV1;
typedef struct MantisEvidenceSourceV1 MantisEvidenceSourceV1;
typedef struct MantisAcknowledgementV1 MantisAcknowledgementV1;
typedef struct MantisEmitterCommandV1 MantisEmitterCommandV1;
typedef struct MantisStateObservationV1 MantisStateObservationV1;
typedef struct MantisExposureEvidenceV1 MantisExposureEvidenceV1;
typedef struct MantisExposureAssociationV1 MantisExposureAssociationV1;
typedef struct MantisSyncEvidenceV1 MantisSyncEvidenceV1;
typedef struct MantisCameraFrameEvidenceV1 MantisCameraFrameEvidenceV1;
typedef struct MantisExposureEffectiveStateV1 MantisExposureEffectiveStateV1;
typedef struct MantisCameraEffectiveStateV1 MantisCameraEffectiveStateV1;
typedef struct MantisEmitterEvidenceV1 MantisEmitterEvidenceV1;
typedef struct MantisCameraParticipantV1 MantisCameraParticipantV1;
typedef struct MantisParticipantsV1 MantisParticipantsV1;
typedef struct MantisTriggerIntentV1 MantisTriggerIntentV1;
typedef struct MantisCaptureIntentV1 MantisCaptureIntentV1;
typedef struct MantisEmitterIntentV1 MantisEmitterIntentV1;
typedef struct MantisAcquisitionStepV1 MantisAcquisitionStepV1;
typedef struct MantisRunBoundsV1 MantisRunBoundsV1;
typedef struct MantisAcquisitionProgramV1 MantisAcquisitionProgramV1;
typedef struct MantisTriggerEventV1 MantisTriggerEventV1;
typedef struct MantisImplementationIdentityV1 MantisImplementationIdentityV1;
typedef struct MantisLossAccountingV1 MantisLossAccountingV1;
typedef struct MantisUnresolvedRequestV1 MantisUnresolvedRequestV1;
typedef struct MantisAcquisitionEvidenceV1 MantisAcquisitionEvidenceV1;
typedef struct MantisEmitterPatternIdentityV1 MantisEmitterPatternIdentityV1;
typedef struct MantisLineIdentityV1 MantisLineIdentityV1;
typedef struct MantisProgramCorrelationV1 MantisProgramCorrelationV1;
typedef struct MantisPreprocessingTransformV1 MantisPreprocessingTransformV1;
typedef struct MantisObservationKeyV1 MantisObservationKeyV1;
typedef struct MantisLaserObservationContextV1 MantisLaserObservationContextV1;
typedef struct MantisLaserObservationV1 MantisLaserObservationV1;
typedef struct MantisPacketHeaderV1 MantisPacketHeaderV1;
typedef struct MantisDeviceTimestampV1 MantisDeviceTimestampV1;
typedef struct MantisComponentListV1 MantisComponentListV1;
typedef struct MantisMetadataEntryV1 MantisMetadataEntryV1;
typedef struct MantisMetadataV1 MantisMetadataV1;
typedef struct MantisDataPacketV1 MantisDataPacketV1;
typedef struct MantisAcquisitionBundleV1 MantisAcquisitionBundleV1;
typedef struct MantisSemanticPacketV1 MantisSemanticPacketV1;
typedef struct MantisEvidenceAcknowledgementV1 {
    uint32_t struct_size, abi_version, presence;
    MantisAcknowledgementV1 const *value;
} MantisEvidenceAcknowledgementV1;
typedef struct MantisEvidenceAcknowledgementResultV1 {
    uint32_t struct_size, abi_version, presence;
    uint32_t const *value;
} MantisEvidenceAcknowledgementResultV1;
typedef struct MantisEvidenceAcknowledgementStageV1 {
    uint32_t struct_size, abi_version, presence;
    uint32_t const *value;
} MantisEvidenceAcknowledgementStageV1;
typedef struct MantisEvidenceAcquisitionDispositionV1 {
    uint32_t struct_size, abi_version, presence;
    uint32_t const *value;
} MantisEvidenceAcquisitionDispositionV1;
typedef struct MantisEvidenceBundleKeyV1 {
    uint32_t struct_size, abi_version, presence;
    MantisBundleKeyV1 const *value;
} MantisEvidenceBundleKeyV1;
typedef struct MantisEvidenceCaptureModeV1 {
    uint32_t struct_size, abi_version, presence;
    uint32_t const *value;
} MantisEvidenceCaptureModeV1;
typedef struct MantisEvidenceClockMappingEvidenceV1 {
    uint32_t struct_size, abi_version, presence;
    MantisClockMappingEvidenceV1 const *value;
} MantisEvidenceClockMappingEvidenceV1;
typedef struct MantisEvidenceComponentListV1 {
    uint32_t struct_size, abi_version, presence;
    MantisComponentListV1 const *value;
} MantisEvidenceComponentListV1;
typedef struct MantisEvidenceContentReferenceV1 {
    uint32_t struct_size, abi_version, presence;
    MantisContentReferenceV1 const *value;
} MantisEvidenceContentReferenceV1;
typedef struct MantisEvidenceDurationV1 {
    uint32_t struct_size, abi_version, presence;
    int64_t const *value;
} MantisEvidenceDurationV1;
typedef struct MantisEvidenceEmitterCommandV1 {
    uint32_t struct_size, abi_version, presence;
    MantisEmitterCommandV1 const *value;
} MantisEvidenceEmitterCommandV1;
typedef struct MantisEvidenceEmitterStateV1 {
    uint32_t struct_size, abi_version, presence;
    uint32_t const *value;
} MantisEvidenceEmitterStateV1;
typedef struct MantisEvidenceEvidenceKeyV1 {
    uint32_t struct_size, abi_version, presence;
    MantisEvidenceKeyV1 const *value;
} MantisEvidenceEvidenceKeyV1;
typedef struct MantisEvidenceEvidenceRequirementV1 {
    uint32_t struct_size, abi_version, presence;
    uint32_t const *value;
} MantisEvidenceEvidenceRequirementV1;
typedef struct MantisEvidenceExactCalibrationReferenceV1 {
    uint32_t struct_size, abi_version, presence;
    MantisExactCalibrationReferenceV1 const *value;
} MantisEvidenceExactCalibrationReferenceV1;
typedef struct MantisEvidenceExposureAssociationV1 {
    uint32_t struct_size, abi_version, presence;
    MantisExposureAssociationV1 const *value;
} MantisEvidenceExposureAssociationV1;
typedef struct MantisEvidenceExposureEffectiveStateV1 {
    uint32_t struct_size, abi_version, presence;
    MantisExposureEffectiveStateV1 const *value;
} MantisEvidenceExposureEffectiveStateV1;
typedef struct MantisEvidenceExposureEvidenceV1 {
    uint32_t struct_size, abi_version, presence;
    MantisExposureEvidenceV1 const *value;
} MantisEvidenceExposureEvidenceV1;
typedef struct MantisEvidenceFrameSetKeyV1 {
    uint32_t struct_size, abi_version, presence;
    MantisFrameSetKeyV1 const *value;
} MantisEvidenceFrameSetKeyV1;
typedef struct MantisEvidenceGenerationIdV1 {
    uint32_t struct_size, abi_version, presence;
    const char * const *value;
} MantisEvidenceGenerationIdV1;
typedef struct MantisEvidenceHashV1 {
    uint32_t struct_size, abi_version, presence;
    MantisHashV1 const *value;
} MantisEvidenceHashV1;
typedef struct MantisEvidenceImplementationIdentityV1 {
    uint32_t struct_size, abi_version, presence;
    MantisImplementationIdentityV1 const *value;
} MantisEvidenceImplementationIdentityV1;
typedef struct MantisEvidenceNativeTriggerIdentityV1 {
    uint32_t struct_size, abi_version, presence;
    MantisNativeTriggerIdentityV1 const *value;
} MantisEvidenceNativeTriggerIdentityV1;
typedef struct MantisEvidenceObservationDispositionV1 {
    uint32_t struct_size, abi_version, presence;
    uint32_t const *value;
} MantisEvidenceObservationDispositionV1;
typedef struct MantisEvidenceObservationOriginV1 {
    uint32_t struct_size, abi_version, presence;
    uint32_t const *value;
} MantisEvidenceObservationOriginV1;
typedef struct MantisEvidencePatternIdV1 {
    uint32_t struct_size, abi_version, presence;
    const char * const *value;
} MantisEvidencePatternIdV1;
typedef struct MantisEvidencePreprocessingTransformV1 {
    uint32_t struct_size, abi_version, presence;
    MantisPreprocessingTransformV1 const *value;
} MantisEvidencePreprocessingTransformV1;
typedef struct MantisEvidenceProgramCorrelationV1 {
    uint32_t struct_size, abi_version, presence;
    MantisProgramCorrelationV1 const *value;
} MantisEvidenceProgramCorrelationV1;
typedef struct MantisEvidenceRequestIdV1 {
    uint32_t struct_size, abi_version, presence;
    const char * const *value;
} MantisEvidenceRequestIdV1;
typedef struct MantisEvidenceRunIdV1 {
    uint32_t struct_size, abi_version, presence;
    const char * const *value;
} MantisEvidenceRunIdV1;
typedef struct MantisEvidenceRuntimeTimestampV1 {
    uint32_t struct_size, abi_version, presence;
    MantisRuntimeTimestampV1 const *value;
} MantisEvidenceRuntimeTimestampV1;
typedef struct MantisEvidenceSemanticTimestampV1 {
    uint32_t struct_size, abi_version, presence;
    MantisSemanticTimestampV1 const *value;
} MantisEvidenceSemanticTimestampV1;
typedef struct MantisEvidenceSourceFrameKeyV1 {
    uint32_t struct_size, abi_version, presence;
    MantisSourceFrameKeyV1 const *value;
} MantisEvidenceSourceFrameKeyV1;
typedef struct MantisEvidenceStateObservationV1 {
    uint32_t struct_size, abi_version, presence;
    MantisStateObservationV1 const *value;
} MantisEvidenceStateObservationV1;
typedef struct MantisEvidenceStepInstanceV1 {
    uint32_t struct_size, abi_version, presence;
    MantisStepInstanceV1 const *value;
} MantisEvidenceStepInstanceV1;
typedef struct MantisEvidenceSyncEvidenceV1 {
    uint32_t struct_size, abi_version, presence;
    MantisSyncEvidenceV1 const *value;
} MantisEvidenceSyncEvidenceV1;
typedef struct MantisEvidenceTimeIntervalV1 {
    uint32_t struct_size, abi_version, presence;
    MantisTimeIntervalV1 const *value;
} MantisEvidenceTimeIntervalV1;
typedef struct MantisEvidenceTimestampMeaningV1 {
    uint32_t struct_size, abi_version, presence;
    uint32_t const *value;
} MantisEvidenceTimestampMeaningV1;
typedef struct MantisEvidenceTriggerKindV1 {
    uint32_t struct_size, abi_version, presence;
    uint32_t const *value;
} MantisEvidenceTriggerKindV1;
typedef struct MantisEvidenceFloat64V1 {
    uint32_t struct_size, abi_version, presence;
    double const *value;
} MantisEvidenceFloat64V1;
typedef struct MantisEvidenceUInt32V1 {
    uint32_t struct_size, abi_version, presence;
    uint32_t const *value;
} MantisEvidenceUInt32V1;
typedef struct MantisEvidenceUInt64V1 {
    uint32_t struct_size, abi_version, presence;
    uint64_t const *value;
} MantisEvidenceUInt64V1;
struct MantisComponentListV1 {
    uint32_t struct_size, abi_version;
    const char *const *items;
    uint32_t count;
};
struct MantisMetadataEntryV1 {
    uint32_t struct_size, abi_version;
    const char *key, *value;
};
struct MantisMetadataV1 {
    uint32_t struct_size, abi_version;
    const MantisMetadataEntryV1 *items;
    uint32_t count;
};
struct MantisDataTypeV1 {
    uint32_t struct_size, abi_version;
    const char * name;
    uint32_t version;
};
struct MantisHashV1 {
    uint32_t struct_size, abi_version;
    const char * algorithm;
    const char * hex;
};
struct MantisVersionV1 {
    uint32_t struct_size, abi_version;
    uint32_t major;
    uint32_t minor;
    uint32_t patch;
};
struct MantisCalibrationReferenceV1 {
    uint32_t struct_size, abi_version;
    const char * id;
    uint32_t schema_version;
    uint64_t revision;
};
struct MantisClockDomainV1 {
    uint32_t struct_size, abi_version;
    const char * id;
    const char * name;
};
struct MantisCoordinateFrameV1 {
    uint32_t struct_size, abi_version;
    const char * id;
    const char * name;
};
struct MantisSyncGroupV1 {
    uint32_t struct_size, abi_version;
    const char * id;
    uint64_t trigger;
};
struct MantisClockMappingV1 {
    uint32_t struct_size, abi_version;
    MantisClockDomainV1 source;
    MantisClockDomainV1 target;
    double scale;
    double offset_ns;
    double uncertainty_ns;
};
struct MantisStepInstanceV1 {
    uint32_t struct_size, abi_version;
    const char * run_id;
    uint64_t repetition_index;
    uint32_t step_index;
};
struct MantisStreamIdentityV1 {
    uint32_t struct_size, abi_version;
    const char * id;
    const char * generation;
};
struct MantisSourceFrameKeyV1 {
    uint32_t struct_size, abi_version;
    const char * camera;
    MantisStreamIdentityV1 stream;
    uint64_t native_sequence;
};
struct MantisFrameSetKeyV1 {
    uint32_t struct_size, abi_version;
    const char * run_id;
    MantisStreamIdentityV1 stream;
    uint64_t sequence;
};
struct MantisBundleKeyV1 {
    uint32_t struct_size, abi_version;
    const char * run_id;
    uint64_t sequence;
};
struct MantisEvidenceKeyV1 {
    uint32_t struct_size, abi_version;
    const char * run_id;
    uint64_t ordinal;
};
struct MantisTriggerKeyV1 {
    uint32_t struct_size, abi_version;
    const char * run_id;
    const char * source;
    const char * controller_generation;
    uint64_t sequence;
};
struct MantisNativeTriggerIdentityV1 {
    uint32_t struct_size, abi_version;
    const char * controller;
    const char * generation;
    uint64_t value;
};
struct MantisContentReferenceV1 {
    uint32_t struct_size, abi_version;
    const char * id;
    MantisDataTypeV1 type;
    MantisEvidenceHashV1 hash;
    uint64_t revision;
};
struct MantisProgramReferenceV1 {
    uint32_t struct_size, abi_version;
    const char * id;
    MantisEvidenceHashV1 hash;
    MantisEvidenceContentReferenceV1 content;
};
struct MantisExactCalibrationReferenceV1 {
    uint32_t struct_size, abi_version;
    MantisCalibrationReferenceV1 calibration;
    MantisEvidenceContentReferenceV1 content;
};
struct MantisClockIdentityV1 {
    uint32_t struct_size, abi_version;
    MantisClockDomainV1 domain;
    const char * generation;
};
struct MantisSemanticTimestampV1 {
    uint32_t struct_size, abi_version;
    int64_t nanoseconds;
    MantisClockIdentityV1 clock;
};
struct MantisRuntimeTimestampV1 {
    uint32_t struct_size, abi_version;
    int64_t time;
    MantisClockIdentityV1 clock;
};
struct MantisTimeIntervalV1 {
    uint32_t struct_size, abi_version;
    MantisSemanticTimestampV1 start;
    MantisSemanticTimestampV1 end;
};
struct MantisClockMappingEvidenceV1 {
    uint32_t struct_size, abi_version;
    MantisClockMappingV1 mapping;
    const char * source_generation;
    const char * target_generation;
    MantisContentReferenceV1 reference;
};
struct MantisEvidenceSourceV1 {
    uint32_t struct_size, abi_version;
    const char * source;
    uint32_t method;
    MantisEvidenceContentReferenceV1 reference;
};
struct MantisAcknowledgementV1 {
    uint32_t struct_size, abi_version;
    const char * request;
    MantisEvidenceAcknowledgementStageV1 stage;
    MantisEvidenceAcknowledgementResultV1 result;
    MantisEvidenceSourceV1 evidence;
    MantisEvidenceSemanticTimestampV1 time;
    uint32_t scope;
};
struct MantisEmitterCommandV1 {
    uint32_t struct_size, abi_version;
    const char * request;
    const char * target;
    uint32_t state;
    MantisRuntimeTimestampV1 dispatched;
};
struct MantisStateObservationV1 {
    uint32_t struct_size, abi_version;
    MantisEvidenceEmitterStateV1 state;
    uint32_t scope;
    MantisEvidenceSourceV1 evidence;
    MantisEvidenceSemanticTimestampV1 time;
    MantisEvidenceTimeIntervalV1 coverage;
};
struct MantisExposureEvidenceV1 {
    uint32_t struct_size, abi_version;
    MantisEvidenceDurationV1 requested_duration;
    MantisEvidenceDurationV1 startup_readback_duration;
    MantisEvidenceDurationV1 integration_duration;
    MantisEvidenceTimeIntervalV1 interval;
    MantisEvidenceSourceV1 evidence;
    MantisEvidenceFloat64V1 uncertainty_ns;
};
struct MantisExposureAssociationV1 {
    uint32_t struct_size, abi_version;
    MantisSourceFrameKeyV1 frame;
    MantisTriggerKeyV1 trigger;
    uint32_t method;
    MantisEvidenceSourceV1 evidence;
    MantisEvidenceNativeTriggerIdentityV1 native_trigger;
};
struct MantisSyncEvidenceV1 {
    uint32_t struct_size, abi_version;
    MantisSyncGroupV1 group;
    uint32_t quality;
    MantisEvidenceExposureAssociationV1 hardware_association;
};
struct MantisCameraFrameEvidenceV1 {
    uint32_t struct_size, abi_version;
    MantisSourceFrameKeyV1 frame;
    const char * camera_role;
    uint32_t width;
    uint32_t height;
    MantisEvidenceSemanticTimestampV1 source_timestamp;
    MantisEvidenceRuntimeTimestampV1 host_received;
    MantisEvidenceTimestampMeaningV1 timestamp_meaning;
    MantisEvidenceExposureEvidenceV1 exposure;
    MantisEvidenceSyncEvidenceV1 sync;
    MantisEvidenceExactCalibrationReferenceV1 camera_calibration;
    MantisEvidenceExactCalibrationReferenceV1 rig_calibration;
    MantisEvidenceExactCalibrationReferenceV1 original_calibration;
};
struct MantisExposureEffectiveStateV1 {
    uint32_t struct_size, abi_version;
    MantisSourceFrameKeyV1 frame;
    MantisEvidenceEmitterStateV1 state;
    uint32_t scope;
    MantisEvidenceSourceV1 evidence;
    MantisTimeIntervalV1 coverage;
};
struct MantisCameraEffectiveStateV1 {
    uint32_t struct_size, abi_version;
    MantisSourceFrameKeyV1 frame;
    MantisEvidenceExposureEffectiveStateV1 state;
};
struct MantisEmitterEvidenceV1 {
    uint32_t struct_size, abi_version;
    const char * emitter;
    MantisEvidenceEmitterCommandV1 commanded;
    MantisEvidenceAcknowledgementV1 acknowledged;
    MantisEvidenceStateObservationV1 observed;
    MantisCameraEffectiveStateV1 const *exposure_effective;
    uint32_t exposure_effective_count;
};
struct MantisCameraParticipantV1 {
    uint32_t struct_size, abi_version;
    const char * component;
    const char * stream;
    const char * role;
};
struct MantisParticipantsV1 {
    uint32_t struct_size, abi_version;
    MantisCameraParticipantV1 const *cameras;
    uint32_t cameras_count;
    const char * const *emitters;
    uint32_t emitters_count;
    const char * const *controllers;
    uint32_t controllers_count;
};
struct MantisTriggerIntentV1 {
    uint32_t struct_size, abi_version;
    const char * controller;
    const char * request;
    const char * const *endpoints;
    uint32_t endpoints_count;
};
struct MantisCaptureIntentV1 {
    uint32_t struct_size, abi_version;
    MantisEvidenceCaptureModeV1 mode;
    const char * const *cameras;
    uint32_t cameras_count;
    const MantisTriggerIntentV1 *trigger;
};
struct MantisEmitterIntentV1 {
    uint32_t struct_size, abi_version;
    const char * emitter;
    uint32_t state;
};
struct MantisAcquisitionStepV1 {
    uint32_t struct_size, abi_version;
    uint32_t index;
    const char * label;
    MantisEmitterIntentV1 const *emitters;
    uint32_t emitters_count;
    MantisCaptureIntentV1 capture;
    MantisEvidenceEvidenceRequirementV1 evidence_requirement;
    uint32_t required_scope;
    int64_t settle;
    int64_t max_duration;
};
struct MantisRunBoundsV1 {
    uint32_t struct_size, abi_version;
    int64_t max_duration;
    int64_t max_on_duration;
    uint64_t max_step_instances;
    uint64_t max_commands;
    uint64_t max_events;
    uint64_t max_bytes;
    uint64_t max_in_flight_captures;
};
struct MantisAcquisitionProgramV1 {
    uint32_t struct_size, abi_version;
    MantisDataTypeV1 type;
    MantisProgramReferenceV1 identity;
    MantisParticipantsV1 participants;
    MantisAcquisitionStepV1 const *steps;
    uint32_t steps_count;
    uint64_t repetitions;
    MantisRunBoundsV1 bounds;
    uint32_t terminal_policy; /* must be MANTIS_TERMINAL_INHIBIT_AND_ALL_OFF */
};
struct MantisTriggerEventV1 {
    uint32_t struct_size, abi_version;
    MantisDataTypeV1 type;
    MantisTriggerKeyV1 key;
    MantisStepInstanceV1 step;
    const char * request;
    MantisEvidenceNativeTriggerIdentityV1 native_trigger;
    MantisEvidenceTriggerKindV1 kind;
    MantisEvidenceAcknowledgementV1 acknowledgement;
    MantisEvidenceSourceV1 evidence;
    MantisEvidenceSemanticTimestampV1 device_time;
    MantisEvidenceRuntimeTimestampV1 host_received;
    MantisEvidenceRuntimeTimestampV1 host_dispatched;
    MantisEvidenceFloat64V1 uncertainty_ns;
    MantisEvidenceClockMappingEvidenceV1 clock_mapping;
    const char * const *intended_endpoints;
    uint32_t intended_endpoints_count;
    MantisEvidenceComponentListV1 actual_endpoints;
    MantisEvidenceSourceFrameKeyV1 requested_exposure;
    MantisEvidenceExposureAssociationV1 exposure_association;
};
struct MantisImplementationIdentityV1 {
    uint32_t struct_size, abi_version;
    const char * implementation;
    MantisVersionV1 version;
    const char * build;
    MantisEvidenceContentReferenceV1 configuration;
};
struct MantisLossAccountingV1 {
    uint32_t struct_size, abi_version;
    uint32_t kind;
    const char * source;
    MantisEvidenceUInt64V1 count;
    uint32_t reason;
    MantisEvidenceSourceFrameKeyV1 frame;
    MantisEvidenceRequestIdV1 request;
};
struct MantisUnresolvedRequestV1 {
    uint32_t struct_size, abi_version;
    const char * request;
    const char * target;
    uint32_t reason;
};
struct MantisAcquisitionEvidenceV1 {
    uint32_t struct_size, abi_version;
    MantisDataTypeV1 type;
    MantisEvidenceKeyV1 key;
    MantisProgramReferenceV1 program;
    MantisEvidenceStepInstanceV1 step;
    MantisEvidenceKeyV1 const *causal_predecessors;
    uint32_t causal_predecessors_count;
    MantisParticipantsV1 participants;
    MantisImplementationIdentityV1 const *implementations;
    uint32_t implementations_count;
    MantisEmitterEvidenceV1 const *emitters;
    uint32_t emitters_count;
    MantisEvidenceFrameSetKeyV1 frameset;
    MantisCameraFrameEvidenceV1 const *frames;
    uint32_t frames_count;
    MantisTriggerKeyV1 const *triggers;
    uint32_t triggers_count;
    MantisClockMappingEvidenceV1 const *clock_mappings;
    uint32_t clock_mappings_count;
    MantisEvidenceExactCalibrationReferenceV1 rig_calibration;
    MantisEvidenceAcquisitionDispositionV1 disposition;
    uint32_t reason;
    MantisUnresolvedRequestV1 const *unresolved_requests;
    uint32_t unresolved_requests_count;
    MantisLossAccountingV1 const *losses;
    uint32_t losses_count;
    const char * diagnostic;
};
struct MantisEmitterPatternIdentityV1 {
    uint32_t struct_size, abi_version;
    const char * emitter;
    const char * pattern;
    uint64_t revision;
};
struct MantisLineIdentityV1 {
    uint32_t struct_size, abi_version;
    const char * emitter;
    const char * pattern;
    uint64_t pattern_revision;
    const char * local_line;
};
struct MantisProgramCorrelationV1 {
    uint32_t struct_size, abi_version;
    MantisProgramReferenceV1 program;
    MantisStepInstanceV1 step;
};
struct MantisPreprocessingTransformV1 {
    uint32_t struct_size, abi_version;
    double original_from_processed[9];
    MantisEvidenceContentReferenceV1 reference;
};
struct MantisObservationKeyV1 {
    uint32_t struct_size, abi_version;
    MantisEvidenceRunIdV1 run_id;
    const char * producer_stream;
    const char * producer_generation;
    uint64_t sequence;
};
struct MantisLaserObservationContextV1 {
    uint32_t struct_size, abi_version;
    MantisCameraFrameEvidenceV1 source;
    MantisEvidenceFrameSetKeyV1 frameset;
    MantisEvidenceBundleKeyV1 bundle;
    MantisEvidenceContentReferenceV1 raw_input;
    MantisCoordinateFrameV1 optical_frame;
    MantisEvidencePreprocessingTransformV1 preprocessing;
    const char * const *requested_emitters;
    uint32_t requested_emitters_count;
    MantisEmitterEvidenceV1 const *emitter_evidence;
    uint32_t emitter_evidence_count;
    MantisEmitterPatternIdentityV1 const *emitter_patterns;
    uint32_t emitter_patterns_count;
    MantisEvidenceProgramCorrelationV1 correlation;
    MantisEvidenceEvidenceKeyV1 acquisition_evidence;
    MantisTriggerKeyV1 const *triggers;
    uint32_t triggers_count;
    MantisClockMappingEvidenceV1 const *clock_mappings;
    uint32_t clock_mappings_count;
    MantisImplementationIdentityV1 producer;
    MantisEvidenceContentReferenceV1 parameters;
    MantisContentReferenceV1 const *exact_inputs;
    uint32_t exact_inputs_count;
    MantisEvidenceObservationOriginV1 origin;
    MantisEvidenceRuntimeTimestampV1 producer_completed;
    uint32_t packet_quality_flags;
};
struct MantisLaserObservationV1 {
    uint32_t struct_size, abi_version;
    MantisDataTypeV1 type;
    MantisObservationKeyV1 key;
    MantisLaserObservationContextV1 context;
    MantisEvidenceObservationDispositionV1 disposition;
    uint64_t sample_count;
    const char * const *emitter_dictionary;
    uint32_t emitter_dictionary_count;
    MantisLineIdentityV1 const *line_dictionary;
    uint32_t line_dictionary_count;
    MantisAttributeV1 const *attributes;
    uint32_t attributes_count;
    MantisEvidenceImplementationIdentityV1 confidence_interpretation;
    const char * diagnostic;
};
struct MantisDeviceTimestampV1 {
    uint32_t struct_size, abi_version;
    int64_t nanoseconds;
    MantisClockDomainV1 domain;
};
struct MantisPacketHeaderV1 {
    uint32_t struct_size, abi_version;
    uint64_t sequence;
    MantisDeviceTimestampV1 timestamp;
    int64_t received;
    MantisSyncGroupV1 sync;
    uint32_t sync_quality;
    MantisCalibrationReferenceV1 calibration;
    MantisCoordinateFrameV1 frame;
    MantisMetadataV1 metadata;
};
enum { MANTIS_TERMINAL_INHIBIT_AND_ALL_OFF = 0u };
struct MantisDataPacketV1 {
    uint32_t struct_size, abi_version;
    MantisDataTypeV1 type;
    MantisPacketHeaderV1 header;
    const MantisAttributeV1 *attributes;
    uint32_t attribute_count;
    const MantisDataPacketV1 *frames;
    uint32_t frame_count;
};
struct MantisAcquisitionBundleV1 {
    uint32_t struct_size, abi_version;
    MantisDataTypeV1 type;
    MantisBundleKeyV1 key;
    MantisRuntimeTimestampV1 published;
    MantisAcquisitionEvidenceV1 evidence;
    const MantisDataPacketV1 *frameset;
    const MantisTriggerEventV1 *triggers;
    uint32_t trigger_count, member_count; /* exactly 1 + !!frameset + trigger_count <=64 */
};
enum { MANTIS_SEMANTIC_DATA = 0u, MANTIS_SEMANTIC_EVIDENCE = 1u,
       MANTIS_SEMANTIC_TRIGGER = 2u, MANTIS_SEMANTIC_BUNDLE = 3u,
       MANTIS_SEMANTIC_LASER = 4u };
/* Exactly one matching typed pointer, all other pointers NULL. No children here. */
struct MantisSemanticPacketV1 {
    uint32_t struct_size, abi_version, kind;
    const MantisDataPacketV1 *data;
    const MantisAcquisitionEvidenceV1 *evidence;
    const MantisTriggerEventV1 *trigger;
    const MantisAcquisitionBundleV1 *bundle;
    const MantisLaserObservationV1 *laser;
};
typedef int (*MantisSemanticEmitV1)(void *, const MantisSemanticPacketV1 *);
#ifdef __cplusplus
}
#endif
#endif
