#ifndef MANTIS_TEST_PROJECTED_FIXTURE_H
#define MANTIS_TEST_PROJECTED_FIXTURE_H
#include <stdint.h>
enum {
    TEST_NORMAL,
    TEST_GRAPH_NULL,
    TEST_GRAPH_SIZE,
    TEST_GRAPH_VERSION,
    TEST_GRAPH_COUNT,
    TEST_GRAPH_DUPLICATE,
    TEST_GRAPH_PARENT,
    TEST_GRAPH_RELATION,
    TEST_GRAPH_PRESENCE,
    TEST_ZERO_EMIT,
    TEST_DOUBLE_EMIT,
    TEST_WRONG_MEMBER,
    TEST_TOO_MANY_MEMBERS,
    TEST_BAD_FRAMESET,
    TEST_BAD_EVIDENCE,
    TEST_RUN_MISMATCH,
    TEST_NOT_READY,
    TEST_FAILURE,
    TEST_PENDING,
    TEST_EMIT_AFTER_FAILURE,
    TEST_BUNDLE_NULL,
    TEST_BUNDLE_SIZE,
    TEST_BUNDLE_VERSION,
    TEST_BUNDLE_PRESENCE,
    TEST_BAD_STATUS,
    TEST_BAD_ABORT,
    TEST_REJECT_PROGRAM,
    TEST_DESTROY_REFUSE,
    TEST_ACTIVE_RUN,
    TEST_PROGRAM_MISMATCH,
    TEST_IMAGE_NULL,
    TEST_IMAGE_STREAM,
    TEST_IMAGE_IDENTITY,
    TEST_IMAGE_WIDTH,
    TEST_IMAGE_HEIGHT,
    TEST_IMAGE_PREFIX,
    TEST_FRAMESET_STREAM,
    TEST_SUCCESSOR_DUPLICATE,
    TEST_SUCCESSOR_BACKWARD,
    TEST_SUCCESSOR_ORDINAL,
    TEST_SUCCESSOR_CLOCK,
    TEST_SUCCESSOR_CLOCK_GENERATION,
    TEST_SUCCESSOR_TIME,
    TEST_SUCCESSOR_TRIGGER_REUSE,
    TEST_SUCCESSOR_TRIGGER_BACKWARD,
    TEST_SUCCESSOR_CONTROLLER,
    TEST_SUCCESSOR_STREAM,
    TEST_HASH_MISMATCH,
    TEST_HASH_DOWNGRADE,
    TEST_CONTENT_MISMATCH,
    TEST_CONTENT_DOWNGRADE,
    TEST_CONTENT_HASH,
    TEST_EVIDENCE_STEP,
    TEST_EVIDENCE_REPETITION,
    TEST_TRIGGER_STEP,
    TEST_TRIGGER_REPETITION,
    TEST_STATUS_STEP,
    TEST_STATUS_REPETITION,
    TEST_TWO_EMITTERS,
    TEST_ABORT_EMPTY,
    TEST_ABORT_MISSING,
    TEST_ABORT_DUPLICATE,
    TEST_ABORT_FOREIGN,
    TEST_ABORT_UNKNOWN,
    TEST_ABORT_REVERSE,
    TEST_HASH_ESTABLISHED,
    TEST_HASH_UNAVAILABLE,
    TEST_CONTENT_ESTABLISHED,
    TEST_CONTENT_UNAVAILABLE,
    TEST_CONTENT_HASH_UNKNOWN,
    TEST_CONTENT_HASH_UNAVAILABLE,
    TEST_SOURCE_WIDTH,
    TEST_SOURCE_HEIGHT,
    TEST_OUTPUT_FRAMESET_STREAM,
    TEST_GRAPH_NO_FRAMESET,
    TEST_SERVICE_COMPLETE,
    TEST_SERVICE_PENDING,
    TEST_SERVICE_START_FAILURE,
    TEST_SERVICE_STOP_FAILURE,
    TEST_SERVICE_CLOSE_FAILURE,
    TEST_SERVICE_ABORT_STATES,
    TEST_SERVICE_RECORDING_FAILURE,
    TEST_SERVICE_CAPTURE,
    TEST_SERVICE_ABORT_FALSE,
    TEST_SERVICE_TRIGGER,
    TEST_SERVICE_VALIDATE_FAILURE,
    TEST_SERVICE_CALIBRATION_MISMATCH,
    TEST_SERVICE_CALIBRATION_CHANGE,
    TEST_SERVICE_CALIBRATION_EXACT
};
typedef struct TestProjectedControl {
    void (*fault)(uint32_t);
    uint32_t (*pending)(void);
    uint32_t (*destroyed)(void);
    uint32_t (*live_instances)(void);
    uint32_t (*initializations)(void);
    uint32_t (*shutdowns)(void);
    void (*shape)(uint32_t);       /* 0 evidence, 1 frame, 2 trigger, UINT32_MAX script */
    void (*publication)(uint32_t); /* next publication sequence override */
    uint32_t (*opens)(void);
    uint32_t (*validations)(void);
    uint32_t (*prepares)(void);
    uint32_t (*starts)(void);
    uint32_t (*aborts)(void);
    void (*prepare_probe)(void (*)(void *), void *);
    void (*image_geometry)(const char *role, const char *identity, uint32_t width, uint32_t height);
    void (*source_calibration)(const char *id, uint64_t revision);
} TestProjectedControl;
#define TEST_PROJECTED_CONTROL "org.mantis.test.projected-control.v1"
#endif
