# Inspect actual target dependencies, not just source include spellings.
function(mantis_assert_dependency_boundary root forbidden)
    set(pending ${root})
    set(visited)
    while(pending)
        list(POP_FRONT pending current)
        if(current IN_LIST visited)
            continue()
        endif()
        list(APPEND visited ${current})
        if(current MATCHES "${forbidden}")
            message(FATAL_ERROR "Architecture boundary violation: ${root} reaches ${current}")
        endif()
        if(TARGET ${current})
            foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
                get_target_property(dependencies ${current} ${property})
                if(dependencies)
                    foreach(dependency IN LISTS dependencies)
                        # Local implementation targets currently use direct dependencies.
                        # Recognize LINK_ONLY when a static library propagates a private dependency.
                        string(REGEX REPLACE "^\\$<LINK_ONLY:([^>]+)>$" "\\1" dependency "${dependency}")
                        if(TARGET ${dependency})
                            list(APPEND pending ${dependency})
                        endif()
                    endforeach()
                endif()
            endforeach()
        endif()
    endwhile()
endfunction()
foreach(module base memory schema data time spatial calibration device-api pipeline-api artifact-api)
    mantis_assert_dependency_boundary(mantis-${module} "^Qt[0-9]::|^SQLite::|^mantis-(services|client|protocol|.*-runtime)$")
endforeach()
mantis_assert_dependency_boundary(mantis-calibration "^opencv_|^nlohmann_json::|^protobuf::|^mantis-(data|artifact-store|calibration-opencv|calibration-dataset)$")
foreach(frontend mantis-cli mantis-client mantis-studio)
    if(TARGET ${frontend})
        mantis_assert_dependency_boundary(${frontend} "^mantis-(services|service-adapter|device-runtime|pipeline-runtime|plugin-runtime|artifact-store|jobs)$")
    endif()
endforeach()
